Switch to cmake build
Fixes:

```
STEP 7/10: RUN cd llama.cpp/ && make
Makefile:2: *** The Makefile build is deprecated. Use the CMake build instead. For more details, see https://github.com/ggerganov/llama.cpp/blob/master/docs/build.md.  Stop.
Error: building at STEP "RUN cd llama.cpp/ && make": while running runtime: exit status 2
```

Signed-off-by: Braxton Plaxco <bplaxco@redhat.com>